[package]
name = "bisharper-filesystem"
version = "0.1.0"
edition = "2021"

[dependencies]
bisharper-common = { path = "../bisharper-common"}
thiserror = "1.0.57"
bisharper-filesystem_macros = { path = "macros"}